### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by iotech-fvtt** [cirrahn/foundry-polmap#1]
You may have saved my entire hex-crawl campaign you amazing person, you! This is FABULOUS!!!
Do you have a donation thing somewhere so I can buy you a cup of coffee or something? I'm not kidding when I say this mod is going to save my campaign, and I'd like to express my appreciation!

**Comment by cirrahn** [comment]
Thank you so much! I did not, but I have now made a [Patreon](https://www.patreon.com/cirrahn) page (ko-fi sounded good until the bit where it leaks your personal details all over the internet) if you would like to toss me some pennies there. If not, donate to a charity of your choice!
