### ISSUE TITLE
Shading areas only works on first click

### ISSUE THREAD

**Issue by tsnouffer** [cirrahn/foundry-polmap#14]
When I click on my map after Enabling the tool only the first click creates a shaded hex. Subsequent clicks do not create the shading. Similarly, when using the eraser tool only the first click will erase the shading from a hex. Subsequent clicks do not erase shading.

Testing included turning off all other modules. Running in Foundry 11.311

![ScreenFlow](https://github.com/cirrahn/foundry-polmap/assets/142341511/caf6732c-c93c-4c1c-9e18-6a080e9210db)

**Comment by tsnouffer** [comment]
In checking the Console, these messages appear after doing that first click.

![Screenshot_10_28_23__12_20_AM](https://github.com/cirrahn/foundry-polmap/assets/142341511/b5466d62-f690-4f6d-ad3d-6dde2463a233)

**Comment by cirrahn** [comment]
What version of polmap are you using?

**Comment by tsnouffer** [comment]
Hi there. Appears to be 2.1.0. Just installed yesterday.

![image](https://github.com/cirrahn/foundry-polmap/assets/142341511/5fd263b6-185a-4e04-8c90-129c51299297)

**Comment by cirrahn** [comment]
That error would suggest you're not using [Socketlib](https://foundryvtt.com/packages/socketlib), which is a dependency. Do you have Socketlib installed/enabled? And if so, what version?

**Comment by tsnouffer** [comment]
Bingo! I had Socket lib installed but not enabled. Rats. Sorry I missed that.

Last two questions if you don’t mind . . .


  1.  can you tell me what this Marker Tool is for? I can’t figure out its function.
***@***.***


  1.  Do you have a Kofi or something where I can send you a gratuity for developing the module and helping me troubleshoot?

From: cirrahn ***@***.***>
Date: Thursday, November 2, 2023 at 6:47 AM
To: cirrahn/foundry-polmap ***@***.***>
Cc: tsnouffer ***@***.***>, Author ***@***.***>
Subject: Re: [cirrahn/foundry-polmap] Shading areas only works on first click (Issue #14)

That error would suggest you're not using Socketlib<https://foundryvtt.com/packages/socketlib>, which is a dependency. Do you have Socketlib installed/enabled?

**Comment by tsnouffer** [comment]
Bingo! I had Socket lib installed but not enabled. Rats. Sorry I missed that.
 
Last two questions if you don’t mind . . .
 
1) can you tell me what this Marker Tool is for? I can’t figure out its function.

![Foundry_Virtual_Tabletop](https://github.com/cirrahn/foundry-polmap/assets/142341511/5a5c4b81-d89e-40df-82bb-03f375aed750)


2) Do you have a Kofi or something where I can send you a gratuity for developing the module and helping me troubleshoot?

**Comment by cirrahn** [comment]
That button is a "placeholder," the "marker tool" is the only tool and so it is always active.

I do have a barebones Patreon (linked in the repo sidebar) but as I work on this/other projects in fits and starts it would be dishonest of me to expect support. I appreciate the thought all the same!

With Socketlib active, is this issue solved? And are #15 and #16 still issues for you?

**Comment by tsnouffer** [comment]
Got it. 

Yes, activating Socket lib seems to resolve all the issues I was experiencing.
