### ISSUE TITLE
Update for foundry v10?

### ISSUE THREAD

**Issue by Constnt1** [cirrahn/foundry-polmap#5]
Just curious if this project is stull being updated along with foundry?

**Comment by cirrahn** [comment]
Eventually, yeah. I've an ongoing campaign in v9 I don't want to/have the time to move over, which I'm looking to finish before taking the v10 leap.

**Comment by krazmuze** [comment]
I hope you do a parallel install to update the mod rather than waiting for campaign to finish!
It gives the menu but not the submenu.

**Comment by cirrahn** [comment]
Sub on Patreon and I'll consider it! 😉

**Comment by iotech-fvtt** [comment]
o_O

**Comment by tjlanza** [comment]
> I hope you do a parallel install to update the mod rather than waiting for campaign to finish! It gives the menu but not the submenu.

It's worth mentioning that many module developers create things to meet _personal_ needs. For such developers, sharing the work with the community and meeting the community's need is a _secondary_ consideration.

**Comment by cirrahn** [comment]
Update now available!
