### ISSUE TITLE
Hexes don't seem to line up with grids

### ISSUE THREAD

**Issue by Mikkles** [cirrahn/foundry-polmap#6]
* I don't fully remember if this was created in v9 or v10. I believe it has been ported from a v9 game and duplicated.
* This map has a 177 grid; tried to scale up to 200 but problem persisted.

[fvtt-Scene-stolen-lands-(copy).json.txt](https://github.com/cirrahn/foundry-polmap/files/10196801/fvtt-Scene-stolen-lands-.copy.json.txt)

**Comment by cirrahn** [comment]
Should now be fixed in 2.0.1!
