### ISSUE TITLE
Colour Picker is under left navigation menu

### ISSUE THREAD

**Issue by jasharen** [cirrahn/foundry-polmap#7]
Hello,
Awesome mod, loving it :)

One minor issue I am having however, is that when I click on the political button on the toolbar, the colour picker shows up under the menu items instead of to the right of the menu.

Great work!

**Comment by cirrahn** [comment]
I don't seem to be able to reproduce that, here's what mine looks like:

![image](https://user-images.githubusercontent.com/9784519/216823091-327a084e-9f08-4f34-9e4a-33ce9aeba419.png)

Could you post a screenshot, please?

**Comment by cirrahn** [comment]
Could not reproduce
